function init(self)
	-- 在此处添加初始化代码
	-- 了解更多：https://defold.com/manuals/script/
	-- 如果不需要，请删除此函数
end

function final(self)
	-- 在此处添加终结化代码
	-- 了解更多：https://defold.com/manuals/script/
	-- 如果不需要，请删除此函数
end

function update(self, dt)
	-- 在此处添加更新代码
	-- 了解更多：https://defold.com/manuals/script/
	-- 如果不需要，请删除此函数
end

function on_message(self, message_id, message, sender)
	-- 在此处添加消息处理代码
	-- 了解更多：https://defold.com/manuals/message-passing/
	-- 如果不需要，请删除此函数
end

function on_input(self, action_id, action)
	-- 在此处添加输入处理代码。此脚本附加的游戏对象
	-- 必须已获取输入焦点：
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- 所有映射的输入绑定都将被接收。鼠标和触摸输入
	-- 无论发生在屏幕上的哪个位置都会被接收。
	-- 了解更多：https://defold.com/manuals/input/
	-- 如果不需要，请删除此函数
end

function on_reload(self)
	-- 在此处添加重载处理代码
	-- 了解更多：https://defold.com/manuals/hot-reload/
	-- 如果不需要，请删除此函数
end