function init(self)
	-- 在此处添加初始化代码
	-- 了解更多：https://defold.com/manuals/script/
	-- 如不需要可删除此函数
end

function final(self)
	-- 在此处添加终结化代码
	-- 了解更多：https://defold.com/manuals/script/
	-- 如不需要可删除此函数
end

function update(self, dt)
	-- 在此处添加更新代码
	-- 了解更多：https://defold.com/manuals/script/
	-- 如不需要可删除此函数
end

function on_message(self, message_id, message, sender)
	-- 在此处添加消息处理代码
	-- 了解更多：https://defold.com/manuals/message-passing/
	-- 如不需要可删除此函数
end

function on_reload(self)
	-- 在此处添加重载处理代码
	-- 了解更多：https://defold.com/manuals/hot-reload/
	-- 如不需要可删除此函数
end